version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - ./:/app

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: stefan
      POSTGRES_PASSWORD: 123
      POSTGRES_HOST_AUTH_METHOD: trust
